### ISSUE TITLE
Cannot test locally

### ISSUE THREAD

**Issue by GoulartNogueira** [jakjus/serverless-discord-bot#4]
When using ```sam local start-api``` (of course, routing with ```ngrok http 3000```) I can register functions, and even setup the interactions endpoint URL.
But when I try to run the command from discord, it throws an error "TopicArn Reason: An ARN must have at least 6 elements, not 1"
And I've spent days trying to workaround that, with no success.

Is there a good way to test it locally?

**Comment by jakjus** [comment]
My guess is, that because of the complex architecture, `sam local start-api` is not enough to test locally. The reason is, that we split proxy the requests and pass it to the queuing service (AWS SNS). And this error (TopicArn) suggests me, that it tries to put an object into the Topic, which is a SNS component. In order for testing to work locally, you would have not to only "start-api" but also start Amazon SNS locally.

You may probably simplify the architecture to only use API Gateway and one Lambda (like it is with my other repository), but then the local dev would only cover a part of the architecture.

Also, you can find a way to run AWS SNS locally. I know DynamoDB can be run locally (and it is also on my Medium), but I don't know about AWS SNS.
